name: RageGames
api: 4.0.0
version: 1.0.1
main: RG\Main
author: xZeroStorm
commands:
        rg:
            description: "RageGames Commands"
        leave:
            description: "Verlässt RageGames Runde"
